### PR TITLE
WhiteSource Artifactory Plugin 

### PR DESCRIPTION
**Pull request by annarozin**
This plugin contains 3 files 
1. whitesource-artifactory-plugin.groovy
2. whitesource-artifactory-plugin.properties
3. README.md

### CODE REVIEW

**Comment by markgalpin** [comment]
@annarozin Thanks for this PR.  Sorry for the delay in response 

Two questions:
1.)  the CheckItem function does not appear to be being used, should it be removed prior to the PR being submitted?

2.) On the updateRepoWithWhiteSource function, what would actually be the recommended best practice for running this.  Typically in minutes, hours, days?

3.)  We would like to be able to test this.  Is there a location/api key we can test against?  (Feel free to provide via private e-mail)

Regards,
Mark

**Comment by DarthFennec** [comment]
I have a couple questions as well:

1. Not a big deal, but while I was looking over the code, this line jumped out at me (line 190):

 ```groovy
DependencyInfo dependencyInfo = new DependencyInfo(repositories.getFileInfo(sha1ToItemMap.get(key).getRepoPath()).getChecksumsInfo().getSha1())
```

 It seems to me that this could be written as follows:

 ```groovy
DependencyInfo dependencyInfo = new DependencyInfo(key)
```
2. I would like to change the URLs for the dependency JARs to be JCenter URLs, rather than Maven Central ones. Also, I would like to add a `setup.groovy` file, which a few of the other plugins in this repository have. This file is run automatically by [`artifactory-user-plugins-devenv`](https://github.com/JFrogDev/artifactory-user-plugins-devenv) whenever a plugin is loaded, and allows arbitrary setup actions such as dependency installation. This helps things like development and testing go more smoothly.

 So, as long as these changes are okay with you, I can add them after the pull request is accepted.

Thanks,
Travis

**Comment by markgalpin** [comment]
Thanks for your update!  We will review tomorrow for a last check and then hopefully run tests.  You don't by any chance have a specific automated test function we could run?

**Comment by annarozin** [comment]
Sorry, I don't have a specific automated test function.
You can add item to Artifactory repo and it will invoke the "afterCreate"
method.


On Thu, Apr 14, 2016 at 8:27 AM, Mark Galpin <notifications@github.com>
wrote:

> Thanks for your update! We will review tomorrow for a last check and then
> hopefully run tests. You don't by any chance have a specific automated test
> function we could run?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/JFrogDev/artifactory-user-plugins/pull/52#issuecomment-209769882>
>



-- 
Anna Rozin, Software Engineer,
WhiteSource,
anna@whitesourcesoftware.com <anna@whitesourcesoftware.com>
http://www.whitesourcesoftware.com/

**Pull request merged**
