### PR TITLE
Conda plugin for Artifactory

### PR DESCRIPTION
**Pull request by Bezier89**

### CODE REVIEW

**Comment by DarthFennec** [comment]
Excellent! If you've signed the [CLA](https://github.com/JFrogDev/artifactory-user-plugins/blob/master/CONTRIBUTING.md), I'll be happy to merge it.

**Comment by Bezier89** [comment]
Done!

**Comment by DarthFennec** [comment]
Cool! Merged. Thank you for contributing.

**Comment by DarthFennec** [comment]
I've added a test and a readme file as well.

**Comment by Bezier89** [comment]
Awesome, thanks!

**Comment by danielfrg** [comment]
Thank you for this!

**Pull request merged**
