### PR TITLE
Howto Eclipse & Maven tips for users plugins development

### PR DESCRIPTION
**Pull request by axel3rd**
Because contributing to users plugins development with Eclipse could be not easy when you are not familiar with Groovy & Artifactory, this little howto.

**NB**: SonarQube configuration added because this is a good practice ... for people having SonarQube & Groovy plugin installed somewhere :-)

### CODE REVIEW

**Comment by DarthFennec** [comment]
Hi, thank you for the PR! Actually, we already have a recommended solution for this. We internally use https://github.com/JFrogDev/artifactory-user-plugins-devenv for our plugin development. It's a smallish gradle project that will automatically do most of the things you documented, including downloading and starting an Artifactory instance on port 8088, setting its auto reload property, linking plugins and tests to it, and of course running said tests. It's also designed to be used from either IntelliJ IDEA or Eclipse, although it's also easy to use in the terminal.

**Comment by axel3rd** [comment]
Grrr not seen before ^^. 

It is written *"Windows OS is not supported"* but there is a BAT ... so I will test it.
Perhaps I will update this PR with just the [artifactory-user-plugins-devenv](https://github.com/JFrogDev/artifactory-user-plugins-devenv) link on the `README.md` :-)

**Comment by DarthFennec** [comment]
Ah ... Gradle automatically generates that BAT file for new projects, but the devenv actually makes heavy use of bash commands and scripts, so I doubt it will run in Windows. It may be possible to run it in cygwin or msys, but I haven't tried.

**Comment by axel3rd** [comment]
> but the devenv actually makes heavy use of bash commands and scripts, so I doubt it will run in Windows.

Confirmed ... and when you work behind a corporate proxy, it worse.

=> Perhaps this PR has sens as *poor solution* for Windows & Eclipse & Maven dev ? 
- `.gitignore` / `pom.xml` / `sonar-project.properties` stay here
- Update of `README.md` with a link to [artifactory-user-plugins-devenv](https://github.com/JFrogDev/artifactory-user-plugins-devenv)
- Another PR with an update (new chapter) on [artifactory-user-plugins-devenv/README.md](https://github.com/JFrogDev/artifactory-user-plugins-devenv/blob/master/README.md) as degraded Maven solution
?

**Comment by DarthFennec** [comment]
I agree, that sounds like a good approach. Although, maybe instead of adding it to the user-plugins-devenv README, add a separate markdown file with the information and link it from the README ... that way it's accessible to those who need it, without crowding the README file with information not directly related to the project.

**Comment by axel3rd** [comment]
PR updated as mentioned, please see [artifactory-user-plugins-devenv #6](https://github.com/JFrogDev/artifactory-user-plugins-devenv/pull/6) as complement.

**Comment by DarthFennec** [comment]
I feel like the link to `user-plugins-devenv` should be an absolute url, rather than a relative one. Other than that, looks good to me.

**Comment by axel3rd** [comment]
> link to user-plugins-devenv should be an absolute url, rather than a relative one

done.

**Comment by DarthFennec** [comment]
Cool, merged. Thanks!

**Comment by axel3rd** [comment]
Thanks

**Pull request merged**
