### PR TITLE
Add promotion replication to buildSync plugin 

### PR DESCRIPTION
**Pull request by elioengcomp**
Add promotion replication to buildSync plugin push and pull configurations.
This first solution requires `ignoreStartDate` set to `true` until this [bug](https://www.jfrog.com/jira/browse/RTFACT-15799) is fixed.

### CODE REVIEW

**Comment by DarthFennec** [comment]
Looks good to me. I'll wait on the merge in case @markgalpin wants to take a look.

**Comment by markgalpin** [comment]
Shouldn't the scenario where the inputs are in conflict (the ignore start date is set to false, but the promotion sync is true) be a 422 or a 409, not a 400?  400 is reserved for malformed requests, a correctly formed but invalid request should be a 422, as I read it, although a 409 seems well in-line with when artifactory issues 409s.

Other than that LGTM, though I did not thoroughly review the business logic/test logic.

**Comment by elioengcomp** [comment]
@markgalpin I've changed to 409. Tks!

**Comment by DarthFennec** [comment]
422 is WebDAV, so I don't expect it's applicable here?

Both of the inputs are in the config file on the server, right? Neither of them come from the request. So that would be a 500 I'd think. You could definitely argue for 409 too though, I don't think there's a problem leaving it as that.

**Pull request merged**
